Vagrant.configure("2") do |config|
  # base image
  config.vm.box = "ubuntu/trusty64"

  # setup a private network to the host machine
  config.vm.network "private_network", ip: "192.168.46.100"

  # share the folder
  config.vm.synced_folder "../", "/opt/service-profile"
  config.vm.synced_folder "../../xos", "/opt/xos", create: true
  config.vm.synced_folder "../../xos_services", "/opt/xos_services", create: true
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # increase RAM
  config.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id,'--memory', '4096']
  end

 end
