# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.synced_folder "../", "/home/vagrant/service-profile"
  config.vm.synced_folder "../../xos", "/home/vagrant/xos", create: true
  config.vm.synced_folder "../../xos_services", "/home/vagrant/xos_services", create: true
  config.vm.synced_folder "../../xos_libraries", "/home/vagrant/xos_libraries", create: true
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "arizona" do |d|
    d.vm.network "forwarded_port", guest: 9999, host: 9990
    d.vm.network "private_network", ip: "192.168.33.10"
    d.vm.provider "virtualbox" do |vb|
       vb.memory = "1024"
    end
  end

  config.vm.define "utah" do |d|
    d.vm.network "forwarded_port", guest: 9999, host: 9991
    d.vm.network "private_network", ip: "192.168.33.11"
    d.vm.provider "virtualbox" do |vb|
       vb.memory = "1024"
    end
  end

  config.vm.define "global" do |d|
    d.vm.network "forwarded_port", guest: 9999, host: 9999
    d.vm.network "private_network", ip: "192.168.33.2"
    d.vm.provider "virtualbox" do |vb|
       vb.memory = "1024"
    end
  end

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y apt-transport-https ca-certificates git
    sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    echo deb https://apt.dockerproject.org/repo ubuntu-trusty main | sudo tee /etc/apt/sources.list.d/docker.list
    sudo apt-get update
    sudo apt-get install -y git docker-engine python-pip
    sudo pip install docker-compose
    sudo groupadd docker
    sudo usermod -aG docker vagrant
  SHELL
end
